# Generated by Django 4.2 on 2025-01-16 21:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('JUEGOS', 'Juegos Usados'), ('CONSOLAS', 'Consolas Usadas')], max_length=50, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('cedula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='La cédula debe tener al menos 10 dígitos.'), django.core.validators.RegexValidator('^\\d+$', message='La cédula debe contener solo números.')], verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10, message='El número de teléfono debe tener al menos 10 dígitos.'), django.core.validators.RegexValidator('^\\d+$', message='El número de teléfono debe contener solo números.')], verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genero_videojuegos', models.CharField(choices=[('ACCION', 'Accion'), ('AVENTURA', 'Aventura'), ('DEPORTE', 'deporte'), ('RPG', 'rpg'), ('ARCADE', 'Arcade'), ('PLATAFORMAS', 'Plataformas'), ('DISPAROS', 'Disparos')], max_length=50, verbose_name='Genero videojuegos')),
                ('tipo_consola', models.CharField(choices=[('PS2', 'Play station 2'), ('PS3', 'Play station 3'), ('PS4', 'Play station 4'), ('PS5', 'Play station 5'), ('XBOX', 'Xbox'), ('NINTENDO', 'Nintendo Swich')], max_length=50, verbose_name='Consolas de videojuegos')),
                ('imagenes', models.ImageField(upload_to='productos_images')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_transaccion', models.DateField(auto_now_add=True)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comprador', to='tienda.cliente')),
                ('productos', models.ManyToManyField(related_name='Compras', to='tienda.producto')),
            ],
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cedula'], name='tienda_clie_cedula_1b6943_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['categoria'], name='tienda_cate_categor_950bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre_producto'], name='tienda_prod_nombre__e85600_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio'], name='tienda_prod_precio_67adcf_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['producto'], name='tienda_inve_product_34c6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['fecha_transaccion'], name='tienda_comp_fecha_t_448aee_idx'),
        ),
    ]
