# Generated by Django 4.2 on 2025-01-20 03:25

from django.db import migrations

def populate_catalogo(apps, schema_editor):
    
    Catalogo = apps.get_model('tienda', 'Categoria')
    
    Catalogo.objects.create(categoria='JUEGOS')
    Catalogo.objects.create(categoria='CONSOLAS')

class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(populate_catalogo),
    ]
