# Generated by Django 4.2 on 2025-01-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20250120_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero_videojuegos',
            field=models.CharField(blank=True, choices=[('ACCION', 'Accion'), ('AVENTURA', 'Aventura'), ('DEPORTE', 'deporte'), ('RPG', 'rpg'), ('ARCADE', 'Arcade'), ('PLATAFORMAS', 'Plataformas'), ('DISPAROS', 'Disparos')], max_length=50, null=True, verbose_name='Genero videojuegos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_consola',
            field=models.CharField(blank=True, choices=[('PS2', 'Play station 2'), ('PS3', 'Play station 3'), ('PS4', 'Play station 4'), ('PS5', 'Play station 5'), ('XBOX', 'Xbox'), ('NINTENDO', 'Nintendo Swich')], max_length=50, null=True, verbose_name='Consolas de videojuegos'),
        ),
    ]
