# Generated by Django 4.2 on 2025-02-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_detallecompra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
